name: delete-pipeline-CI
on: delete
jobs:
  build:
    name: "Trigger pipeline when branch created"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Trigger Branch Name
      shell: bash
      run: |
           echo "Action triggered"
           echo ${{ github.ref }}
           export branch_name=${{ github.event.ref }}
           echo "Branch Name ="$branch_name
           if [ "$branch_name" == "release"* ]
           then
             echo "Release branch deleted"
           else
             echo "Release branch is not deleted"
           fi
           
