name: CI
on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: "Create Flyway DB deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_TAPAS }}
    - name: Extract Branch Name1
      shell: bash
      run: |
           export CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
           echo "Current Branch " $CURRENT_BRANCH
           echo "GIT HUB TOKEN "$GITHUB_TOKEN
           export PARENT_BRANCH=${{ github.base_ref }}
           echo "PARENT Branch " $PARENT_BRANCH
           echo "::set-env name=CURRENT_BRANCH::$CURRENT_BRANCH"
           echo "::set-env name=PARENT_BRANCH::$PARENT_BRANCH"
           if [ "$CURRENT_BRANCH" == "develop" ] || [ "$CURRENT_BRANCH" == "release" ] || [ "$CURRENT_BRANCH" == "master" ]
           then
              export MERGED_BRANCH=$CURRENT_BRANCH
           else
              export MERGED_BRANCH=$CURRENT_BRANCH
           fi
           echo "::set-env name=MERGED_BRANCH::$PARENT_BRANCH"
      id: extract_branch
    - name: Pull request merged
      if: github.event.pull_request.merged == true
      shell: bash
      run: |
            echo running on current branch $CURRENT_BRANCH
            echo parent branch $PARENT_BRANCH
            URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
            FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
            echo "Changed Files " $FILES
            git branch
            git config --global user.name "Tapas Chakraborty"
            git config --global user.email "tcstapas@yahoo.co.uk"
            git pull
            git checkout $PARENT_BRANCH
            git branch
            cd src/main/flyway
            ls
            chmod +x flyway-conversion.sh
            if [ "$CURRENT_BRANCH" != *"develop"* ] || [ "$CURRENT_BRANCH" != *"release"* ]
            then
              git config --global user.name "Tapas Chakraborty"
              git config --global user.email "tcstapas@yahoo.co.uk"
              ./flyway-conversion.sh $FILES $PARENT_BRANCH
            fi
            ls -R
