name: CI

on: 
  pull_request:
    types: [closed]
 

jobs:
  merge-PR:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Pull request merged
      if: github.action == 'closed' && github.pull_request.merged == 'true'
      run: ls - R
