name: CI
on: 
  pull_request:
    types: opened
  push:
    branches: master
jobs:
  build:
    name: "Create Flyway DB deployment - 1"
    runs-on: ubuntu-latest
    steps:
    - name: Extract Branch Name
      shell: bash
      run: echo running on branch ${GITHUB_REF##*/}
      id: extract_branch
    - name: Pull request merged
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      shell: bash
      run: |
            echo ${{ steps.extract_branch.output.branch }}
            ls -R
