name: CI
on: 
  pull_request:
    types: opened
  push:
    branches: master
jobs:
  build:
    name: "Create Flyway DB deployment - 1"
    runs-on: ubuntu-latest
    steps:
    - name: Pull request merged
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      shell: bash
      run: |
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
            ls -R
