name: CI
on: 
  pull_request:
    types: opened
  push:
    branches: master
jobs:
  build:
    name: "Create Flyway DB deployment - 1"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Branch Name
      shell: bash
      run: echo running on branch ${GITHUB_REF##*/}
      id: extract_branch
    - name: Pull request merged
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      shell: bash
      run: |
            echo running on branch ${GITHUB_REF##*/}
            git branch
            git config --global user.name "Tapas Chakraborty"
            git config --global user.email "tcstapas@yahoo.co.uk"
            cp README.md README1.md
            git add .
            git commit -m "Copied files"
            git push
            ls -R
