name: CI
on: 
  pull_request:
    types: opened
  push:
    branches: master
              develop
jobs:
  build:
    name: "Create Flyway DB deployment - 2"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract Branch Name1
      shell: bash
      run: |
           current_branch=`git rev-parse --abbrev-ref HEAD`
           echo "Current Brncj " $current_branch
           #parent_branch=`git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//'`
           echo '::set-env name=CURRENT_BRANCH::$current_branch'
           #echo '::set-env name=PARENT_BRANCH::$parent_branch'
           if [ "$current_branch" = *"develop"* ] || [ "$current_branch" = *"release"* ]
              push_branch=$current_branch
           else
              push_branch='XX-1111'
           fi
           echo '::set-env name=MERGED_BRANCH::$push_branch'
      id: extract_branch
    - name: Pull request merged
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/$MERGED_BRANCH' }}
      shell: bash
      run: |
            echo running on branch ${GITHUB_REF##*/}
            current_branch=`git rev-parse --abbrev-ref HEAD`
            parent_branch=`git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//'`
            echo '::set-env name=CURRENT_BRANCH::$current_branch'
            if [ "$current_branch" != *"develop"* ] || [ "$current_branch" != *"release"* ]
              git config --global user.name "Tapas Chakraborty"
              git config --global user.email "tcstapas@yahoo.co.uk"
              cp README.md README1.md
              git add .
              git commit -m "Copied files"
              git push
            fi
            ls -R
